### ISSUE TITLE
Rust (Or WASM) in conjunction w Cordova

### ISSUE THREAD

**Issue by tryhardest** [bestia-dev/mem1_phonegap#4]
I see your not too immersed in Cordova (Phonegap as a name kind of is RIP a while back) but Cordova lives strong. Bit confusing yes, but I digress.

Can I reach out to you privately to chat about your use of WASM with Cordova? Very cool to see that you were exploring it.

*Add: this may interest you https://crates.io/crates/cargo-node

**Comment by bestia-dev** [comment]
Thank you, but at the moment I am not interested in Cordova.
